import type { CategorySchema } from '../types';

export const electricalSchema: CategorySchema = {
  key: 'ELECTRICAL',
  label: 'Electrical',
  description: 'No power, fans/lights/sockets not working, exposed wiring, sparking',
  keywords: [
    'electric',
    'electrical',
    'power',
    'current',
    'light',
    'bulb',
    'tube',
    'fan',
    'socket',
    'plug',
    'switch',
    'wiring',
    'wire',
    'short circuit',
    'spark',
    'shock',
    'mcb',
    'fuse',
  ],
  subcategorySlot: 'problem_type',
  dedupWindowHours: 24,
  slots: [
    {
      key: 'safety_hazard',
      question: 'Is any of this happening right now?',
      type: 'multi',
      importance: 'REQUIRED',
      infoGain: 1,
      safetyCritical: true,
      allowSkip: false,
      criticalValues: ['SMOKE', 'BURNING_SMELL', 'SPARKING', 'SHOCK'],
      options: [
        { value: 'SMOKE', label: 'Smoke', hazard: 'SMOKE', hints: ['smoke', 'smoking', 'smoky'] },
        { value: 'BURNING_SMELL', label: 'Burning smell', hazard: 'BURNING_SMELL', hints: ['burning smell', 'burnt smell', 'smells burnt', 'burning'] },
        { value: 'SPARKING', label: 'Sparking', hazard: 'SPARKING', hints: ['spark', 'sparking', 'sparks', 'short circuit'] },
        {
          value: 'EXPOSED_WIRE',
          label: 'Exposed / hanging wires',
          hazard: 'EXPOSED_WIRE',
          // "exposed electrical wiring" is the spec's own §7 example sentence, and
          // an intervening word defeats phrase matching — so it is listed too.
          hints: [
            'exposed wire',
            'exposed wiring',
            'exposed electrical wiring',
            'hanging wire',
            'open wire',
            'live wire',
            'bare wire',
          ],
        },
        { value: 'SHOCK', label: 'Someone got a shock', hazard: 'ELECTRIC_SHOCK', hints: ['shock', 'shocked', 'electrocut'] },
        { value: 'NONE', label: 'None of these', hints: ['nothing like that', 'no hazard'] },
      ],
      unsureDefault: 'NONE',
    },
    {
      key: 'person_at_risk',
      question: 'Is anyone in immediate danger, or is the area accessible to people right now?',
      type: 'boolean',
      importance: 'REQUIRED',
      infoGain: 1,
      safetyCritical: true,
      signal: 'PERSON_AT_RISK',
      allowSkip: false,
      criticalValues: [true],
      askIf: {
        slot: 'safety_hazard',
        op: 'in',
        value: ['SMOKE', 'BURNING_SMELL', 'SPARKING', 'EXPOSED_WIRE', 'SHOCK'],
      },
      unsureDefault: true,
    },
    {
      key: 'problem_type',
      question: 'What is the electrical problem?',
      type: 'enum',
      importance: 'REQUIRED',
      infoGain: 0.9,
      options: [
        { value: 'NO_POWER', label: 'No power in the area', hints: ['no power', 'power cut', 'no current', 'no electricity', 'power gone'] },
        { value: 'LIGHT_NOT_WORKING', label: 'Light not working', hints: ['light', 'bulb', 'tube light', 'tubelight'] },
        { value: 'FAN_NOT_WORKING', label: 'Fan not working', hints: ['fan'] },
        { value: 'SOCKET_NOT_WORKING', label: 'Socket / plug point not working', hints: ['socket', 'plug point', 'switch board', 'switchboard', 'charging point'] },
        { value: 'AC_NOT_WORKING', label: 'AC not working', hints: ['ac not', 'air conditioner', 'air conditioning'] },
        {
          value: 'EXPOSED_WIRING',
          label: 'Exposed or damaged wiring',
          hazard: 'EXPOSED_WIRE',
          hints: ['exposed wire', 'exposed wiring', 'exposed electrical wiring', 'hanging wire', 'damaged wire', 'live wire', 'bare wire'],
        },
        { value: 'FREQUENT_TRIPPING', label: 'Power keeps tripping', hints: ['trip', 'tripping', 'mcb', 'fuse blow', 'keeps going off'] },
      ],
      unsureDefault: 'NO_POWER',
    },
    {
      key: 'location',
      question: 'Where is this? (building, floor or room)',
      type: 'location',
      importance: 'REQUIRED',
      infoGain: 1,
      placeholder: 'e.g. Boys Hostel A, room 214',
      unsureDefault: null,
    },
    {
      key: 'scope',
      question: 'How much of the area is affected?',
      type: 'enum',
      importance: 'RECOMMENDED',
      infoGain: 0.9,
      priorityDiscriminating: true,
      signal: 'SCOPE',
      options: [
        { value: 'ONLY_ME', label: 'Just my room / desk', hints: ['only my room', 'just my room', 'my room only'] },
        { value: 'FEW', label: 'A few rooms', hints: ['few rooms', 'couple of rooms', 'some rooms'] },
        { value: 'MANY', label: 'The whole floor', hints: ['whole floor', 'entire floor', 'all rooms on'] },
        { value: 'BUILDING', label: 'The whole building', hints: ['whole building', 'entire building', 'whole block', 'entire hostel'] },
        { value: 'CAMPUS', label: 'Across campus', hints: ['whole campus', 'across campus'] },
      ],
    },
    {
      key: 'duration',
      question: 'How long has it been like this?',
      type: 'enum',
      importance: 'RECOMMENDED',
      infoGain: 0.7,
      priorityDiscriminating: true,
      signal: 'DURATION',
      options: [
        { value: 'JUST_NOW', label: 'Just started', hints: ['just now', 'just started', 'right now', 'a few minutes'] },
        { value: 'TODAY', label: 'Since today', hints: ['since morning', 'since today', 'all day', 'today'] },
        { value: 'ONE_DAY', label: 'More than a day', hints: ['since yesterday', 'more than a day', 'last night'] },
        { value: 'MULTI_DAY', label: 'Several days', hints: ['for days', 'several days', 'a week', 'past week'] },
      ],
    },
    {
      key: 'impact',
      question: 'Is this blocking anything urgent?',
      type: 'enum',
      importance: 'RECOMMENDED',
      infoGain: 0.6,
      priorityDiscriminating: true,
      signal: 'IMPACT',
      options: [
        { value: 'EXAM', label: 'An exam', hints: ['exam', 'test', 'viva'] },
        { value: 'CLASS', label: 'A class', hints: ['class', 'lecture', 'lab session'] },
        { value: 'ASSIGNMENT', label: 'An assignment deadline', hints: ['assignment', 'deadline', 'submission'] },
        { value: 'NONE', label: 'Nothing urgent', hints: ['nothing urgent', 'not urgent'] },
      ],
    },
    {
      key: 'details',
      question: 'Anything else we should know?',
      type: 'text',
      importance: 'OPTIONAL',
      infoGain: 0.2,
      placeholder: 'Optional',
    },
  ],
};
