import type { CategorySchema } from '../types';

export const networkSchema: CategorySchema = {
  key: 'NETWORK',
  label: 'WiFi / Internet',
  description: 'WiFi not working, slow internet, cannot log in to the campus network',
  keywords: ['wifi', 'wi-fi', 'internet', 'network', 'connection', 'lan', 'ethernet', 'router', 'hotspot'],
  subcategorySlot: 'problem_type',
  dedupWindowHours: 24,
  slots: [
    {
      key: 'problem_type',
      question: 'What exactly is happening with the network?',
      type: 'enum',
      importance: 'REQUIRED',
      infoGain: 0.9,
      options: [
        {
          value: 'NO_CONNECTION',
          label: 'No connection at all',
          hints: [
            'no connection',
            'no internet',
            'not working',
            'isnt working',
            'is down',
            'wifi down',
            'no wifi',
            'dead',
            'not connecting',
          ],
        },
        { value: 'SLOW', label: 'Very slow', hints: ['slow', 'sluggish', 'buffering', 'lagging', 'crawl'] },
        {
          value: 'KEEPS_DISCONNECTING',
          label: 'Keeps disconnecting',
          hints: ['disconnect', 'keeps dropping', 'drops', 'reconnect', 'unstable', 'intermittent'],
        },
        {
          value: 'CANT_LOGIN',
          label: "Can't log in / authentication fails",
          hints: ['cant log in', 'cannot log in', 'login', 'log in', 'password not', 'authentication', 'portal'],
        },
        { value: 'WEAK_SIGNAL', label: 'Weak or no signal', hints: ['weak signal', 'no signal', 'poor signal', 'one bar'] },
      ],
      extractHints: ['wifi', 'internet', 'network'],
      unsureDefault: 'NO_CONNECTION',
    },
    {
      key: 'location',
      question: 'Where are you facing this? (building, floor or room)',
      type: 'location',
      importance: 'REQUIRED',
      infoGain: 1,
      placeholder: 'e.g. CSE Block, 2nd floor',
      unsureDefault: null,
    },
    {
      key: 'scope',
      question: 'Is this affecting only you, or others as well?',
      type: 'enum',
      importance: 'RECOMMENDED',
      infoGain: 0.9,
      priorityDiscriminating: true,
      signal: 'SCOPE',
      options: [
        { value: 'ONLY_ME', label: 'Only me', hints: ['only me', 'just me', 'my laptop only', 'only my'] },
        { value: 'FEW', label: 'A few people', hints: ['few of us', 'couple of us', 'some of us'] },
        { value: 'MANY', label: 'Many people here', hints: ['everyone', 'all of us', 'many people', 'nobody can'] },
        { value: 'BUILDING', label: 'The whole building', hints: ['whole building', 'entire building', 'whole block', 'entire block'] },
        { value: 'CAMPUS', label: 'Across campus', hints: ['whole campus', 'across campus', 'entire campus'] },
      ],
    },
    {
      key: 'duration',
      question: 'How long has this been going on?',
      type: 'enum',
      importance: 'RECOMMENDED',
      infoGain: 0.7,
      priorityDiscriminating: true,
      signal: 'DURATION',
      options: [
        { value: 'JUST_NOW', label: 'Just started', hints: ['just now', 'just started', 'right now', 'a few minutes'] },
        { value: 'TODAY', label: 'Since today', hints: ['since morning', 'since today', 'all day', 'today'] },
        { value: 'ONE_DAY', label: 'More than a day', hints: ['since yesterday', 'a day', 'more than a day', 'last night'] },
        { value: 'MULTI_DAY', label: 'Several days', hints: ['for days', 'several days', 'a week', 'past week', 'since monday'] },
      ],
    },
    {
      key: 'impact',
      question: 'Is this blocking anything urgent right now?',
      type: 'enum',
      importance: 'RECOMMENDED',
      infoGain: 0.6,
      priorityDiscriminating: true,
      signal: 'IMPACT',
      options: [
        { value: 'EXAM', label: 'An exam or online test', hints: ['exam', 'online test', 'viva', 'quiz'] },
        { value: 'CLASS', label: 'A class in progress', hints: ['class', 'lecture', 'lab session'] },
        { value: 'ASSIGNMENT', label: 'An assignment deadline', hints: ['assignment', 'submission', 'deadline', 'project due'] },
        { value: 'NONE', label: 'Nothing urgent', hints: ['nothing urgent', 'not urgent'] },
      ],
    },
    {
      key: 'device_type',
      question: 'Which device are you using?',
      type: 'enum',
      importance: 'OPTIONAL',
      infoGain: 0.3,
      options: [
        { value: 'LAPTOP', label: 'Laptop', hints: ['laptop', 'macbook'] },
        { value: 'PHONE', label: 'Phone', hints: ['phone', 'mobile', 'android', 'iphone'] },
        { value: 'DESKTOP', label: 'Lab desktop', hints: ['desktop', 'lab pc', 'lab computer'] },
        { value: 'OTHER', label: 'Something else' },
      ],
    },
    {
      key: 'other_networks_work',
      question: 'Do other networks (like mobile data) work from the same spot?',
      type: 'boolean',
      importance: 'OPTIONAL',
      infoGain: 0.35,
      askIf: { slot: 'problem_type', op: 'in', value: ['NO_CONNECTION', 'CANT_LOGIN', 'WEAK_SIGNAL'] },
    },
    {
      key: 'details',
      question: 'Anything else worth adding?',
      type: 'text',
      importance: 'OPTIONAL',
      infoGain: 0.2,
      placeholder: 'Optional',
    },
  ],
};
