import type { CategorySchema } from '../types';
import { detailsSlot, durationSlot, locationSlot, recurringSlot, scopeSlot } from './shared';

export const sanitationSchema: CategorySchema = {
  key: 'SANITATION',
  label: 'Sanitation / Cleaning',
  description: 'Dirty washrooms, uncollected garbage, bad smell, pest control',
  keywords: [
    'sanitation',
    'cleaning',
    'not cleaned',
    'not been cleaned',
    'never cleaned',
    'no cleaning',
    'unclean',
    'washroom',
    'toilet',
    'bathroom',
    'dirty',
    'garbage',
    'trash',
    'waste',
    'dustbin',
    'smell',
    'stink',
    'toilet dirty',
    'washroom dirty',
    'housekeeping',
    'sweeper',
  ],
  subcategorySlot: 'problem_type',
  dedupWindowHours: 24,
  slots: [
    {
      key: 'problem_type',
      question: 'What needs attention?',
      type: 'enum',
      importance: 'REQUIRED',
      infoGain: 0.9,
      options: [
        {
          value: 'WASHROOM_UNCLEAN',
          label: 'Washroom not cleaned',
          hints: [
            'washroom dirty',
            'toilet dirty',
            'bathroom not cleaned',
            'washroom not cleaned',
            'washroom has not been cleaned',
            'toilet has not been cleaned',
          ],
        },
        { value: 'GARBAGE_OVERFLOW', label: 'Garbage not collected', hints: ['garbage', 'trash', 'dustbin full', 'waste not collected', 'overflowing bin'] },
        { value: 'AREA_UNCLEAN', label: 'Corridor / room not cleaned', hints: ['not cleaned', 'not swept', 'dusty', 'corridor dirty'] },
        { value: 'BAD_SMELL', label: 'Persistent bad smell', hints: ['bad smell', 'foul smell', 'stink', 'stench'] },
        { value: 'SEWAGE', label: 'Sewage or drain overflow', hazard: 'SEWAGE', hints: ['sewage', 'drain overflow', 'manhole', 'open drain'] },
        { value: 'PEST', label: 'Pests or stray animals', hints: ['cockroach', 'rats', 'mosquito', 'flies', 'stray dogs', 'pest'] },
        { value: 'NO_SUPPLIES', label: 'No soap / tissue / water in washroom', hints: ['no soap', 'no tissue', 'no water in washroom', 'empty dispenser'] },
        { value: 'BROKEN_FIXTURE', label: 'Broken washroom fixture', hints: ['flush broken', 'tap broken', 'door broken', 'mirror broken'] },
      ],
      extractHints: ['cleaning', 'sanitation'],
      unsureDefault: 'AREA_UNCLEAN',
    },
    locationSlot({ question: 'Where is this? (building, floor or washroom)' }),
    scopeSlot({
      question: 'How widespread is it?',
      options: [
        { value: 'ONLY_ME', label: 'One room / fixture', hints: ['one room', 'my room', 'one toilet'] },
        { value: 'FEW', label: 'A few spots', hints: ['few spots', 'couple of places', 'some rooms'] },
        { value: 'MANY', label: 'The whole floor', hints: ['whole floor', 'entire floor', 'all washrooms on'] },
        { value: 'BUILDING', label: 'The whole building', hints: ['whole building', 'entire building', 'whole hostel', 'whole block'] },
      ],
    }),
    durationSlot({ question: 'How long has it been like this?' }),
    recurringSlot({ question: 'Does this keep happening in this spot?' }),
    detailsSlot(),
  ],
};
